### PR TITLE
add dashboard list, pull, push, and migrate commands for current dashboards.

### PR DESCRIPTION
**Pull request by fujiwara**
This PR depends on https://github.com/mackerelio/mackerel-client-go/pull/118.

Add list, pull, and push subcommands to support current dashboards.
Add migrate subcommand to migrate a legacy dashboard to a current dashboard.

### CODE REVIEW

**Comment by lufia** [comment]
Thanks a lot for you contribution!

[question]
I wonder why pull requires `--id` option. What usecase are you expected?

I like to get all dashboards with pull command and store them as JSON files named with id into a directory. As a result, the user can run `mkr dashboards pull && git commit -am`.

**Comment by fujiwara** [comment]
@lufia Thank you for your review!

https://github.com/mackerelio/mkr/pull/353#issuecomment-772291776
> I wonder why pull requires --id option. What usecase are you expected?
> I like to get all dashboards with pull command and store them as JSON files named with id into a directory. As a result, the user can run mkr dashboards pull && git commit -am.

That's right. I required `pull --id` option in developing this code because Dashboard list API doesn't return Widgets elements details.  But it is useful only for debugging.

`pull` became to pull all dashboards and stores these to JSON files named by ID.
at cd0bf62.

I hope to keep `push --file-path` because I sometimes don't want to update all dashboards at once. What do you think about it?

**Comment by lufia** [comment]
> because I sometimes don't want to update all dashboards at once.

Nice. I think so too.

Finally, because in the other commands such as `mkr channels` and `mkr monitors` lists its resources by default, I prefer `mkr dashboards` lists the dashboards.

```go
var commandDashboards = cli.Command{
	Name:  "dashboards",
	Usage: "Manipulate custom dashboards",
	Description: `
    Manipulate custom dashboards. With no subcommand specified, this will show all dashboards. See https://mackerel.io/docs/entry/advanced/cli
`,
	Action: doListDashboards
...
```

**Comment by fujiwara** [comment]
https://github.com/mackerelio/mkr/pull/353#issuecomment-773837745
I see. Fixed at efee40c.

**Comment by lufia** [comment]
Thank you! @fujiwara

**Pull request merged**
