### PR TITLE
[monitors diff] Add the "to-remote" bool flag

### PR DESCRIPTION
**Pull request by yoheimuta**
We are running `mkr monitors diff` to capture the difference by the GUI.

- ref. http://arata.hatenadiary.com/entry/2016/12/11/090000

Current output consists of the difference on the remote server represented by minus and the difference on the local file represented by plus. 
This is useful for the use case that run`mkr monitors push` afterwards. 

However if you run `mkr monitor pull` after `mkr monitor diff`, it is more useful to invert the output and the current one confuses us.

### CODE REVIEW

**Comment by yoheimuta** [comment]
How is the progress ?

**Comment by stefafafan** [comment]
Thank you for the pull request and sorry to make you wait.

It sounds like a good idea to me, but I felt that the option name `to-remote` is a bit confusing.
Maybe an option name of `invert-diff` and changing `isToRemote` to `isInvertedDiff` might be a bit more clearer?

What do you think?

**Comment by yoheimuta** [comment]
Thank you for the review.

> It sounds like a good idea to me, but I felt that the option name to-remote is a bit confusing.
> Maybe an option name of invert-diff and changing isToRemote to isInvertedDiff might be a bit more clearer?

I considered the name `to-remote` from the [diff command spec](http://linuxcommand.org/man_pages/diff1.html). However, it may not be intuitive, and I thought `invert-diff` is easier to understand.

So I will fix it.

**Comment by yoheimuta** [comment]
@stefafafan I fixed 0095564. How about it ?

**Comment by stefafafan** [comment]
@yoheimuta Thank you for the fix.
I am terribly sorry for making you wait again, I talked with the team members and we decided that the option name `reverse` is more appropriate ( `mkr monitors diff --reverse` seems good enough).

Would you be able to make this change? Sorry again about this.

**Comment by yoheimuta** [comment]
@stefafafan I see. I fixed 34ba49c. How about it ?

**Comment by stefafafan** [comment]
@yoheimuta Thanks, it looks good to me!

**Comment by yoheimuta** [comment]
Thanks!

**Pull request merged**
