### PR TITLE
more smaller docker image 

### PR DESCRIPTION
**Pull request by kpango**
This pull request may not be important, but I tried to make the size of DockerImage smaller.

I made two changes
- second stage container changed to scratch
- strip the debugging information  from binary

image-size-diff

### CODE REVIEW

**Comment by itchyny** [comment]
Thank you for your contribution, we are considering accepting this. However, the executable is currently dynamically linked to musl of alpine and changing the second container to scratch causes the error `standard_init_linux.go:190: exec user process caused "no such file or directory"` on my environment. You have to disable cgo add `-extldflags '-static'` to the `ldflags`.

> CGO_ENABLED=0 go build -ldflags "-w -s -extldflags '-static' -X main.gitcommit=$(CURRENT_REVISION)" -o $(BIN) .

**Comment by kpango** [comment]
It means that the net package becomes a dynamic link, I was forgotten.
If you do not use cgo, I think that CGO_ENABLED = 0 may be enough, but I will also include fixes for extldflags.
I'll push it later

**Comment by hayajo** [comment]
依存ライブラリ側でcgo使ってる場合 `GCO_ENABLED=0` してると実行時にうまく動作しないかもしれません。

Dockerfileを
```
FROM golang:alpine3.7 AS builder
RUN apk add --no-cache make git ca-certificates gcc musl-dev
...
```

Makefileを
```
build: deps
	go build -ldflags "-w -s -linkmode external -extldflags \"-static\" -X main.gitcommit=$(CURRENT_REVISION)" -o $(BIN) .
```

にすればcgoもビルドしてstatic linkになると思うのですがいかがでしょうか。

**Comment by kpango** [comment]
In static build of a CGO application, if you use musl-gcc, the calculation result may different from glibc, so I always uses ubuntu etc for build stage.

Another thing may not be required by the mackerel, but if you want to make it smaller binary it is effective to use upx.
The following is an example.

```Dockerfile
FROM ubuntu:18.04 AS builder

ENV APP_NAME mkr

ENV DEBIAN_FRONTEND noninteractive
ENV INITRD No
ENV GOVERSION 1.10.3
ENV GOROOT /opt/go
ENV GOPATH /go
ENV UPX_LEVEL 9

RUN set -eux \
    && apt-get update \
    && apt-get install -y --no-install-recommends \
       ca-certificates \
       build-essential \
       cmake \
       upx \
       curl \
       unzip \
       git \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt

RUN curl -sSL -O "https://storage.googleapis.com/golang/go${GOVERSION}.linux-amd64.tar.gz" \
    && tar zxf "go${GOVERSION}.linux-amd64.tar.gz" \
    && rm "go${GOVERSION}.linux-amd64.tar.gz" \
    && ln -s "${GOROOT}/bin/go" "/usr/bin/" \
    && mkdir "${GOPATH}"

WORKDIR ${GOAPTH}/src/github.com/mackerelio/mkr/
COPY . .
RUN make build
RUN upx -${UPX_LEVEL} -o /usr/bin/mkr ./mkr

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /usr/bin/mkr /usr/local/bin/

ENTRYPOINT ["/usr/local/bin/mkr"]
```

**Comment by hayajo** [comment]
なるほど。
こちらは知りませんでした。ご回答いただきありがとうございます。

> In static build of a CGO application, if you use musl-gcc, the calculation result may different from glibc, so I always uses ubuntu etc for build stage.

**Comment by itchyny** [comment]
Thanks for you explanation and suggestion but we developer team decided to keep using the alpine image and dynamically linked executable. We understand the size of docker image is a kind of concern, but static linking, required to run on the scratch image, will be some pain of maintenance. Honestly we are not confident the build/link flags are correct and we might encounter some trouble new feature not working using the docker image (we don't use the image in our daily use case). Considering the risk of this kind of trouble and maintenancibility, using dynamically linked executable on the alpine image is better option for us. Instead, I opened a new pull request #166 to strip unnecessary information for the executable.
Thanks anyway for your suggestion and closing this pull request in favor of #166.

**Pull request closed without merging**
